# -*- coding: utf-8 -*-
"""kovarshini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuEvNncHch0VbeTxmIK6mYaTJEz14KhF
"""

#Grade calculator
def calculator_grade(marks):

  if 90<= marks <=100:
    return "A"
  elif 80<= marks <=89:
    return "B"
  elif 70<= marks <=79:
    return "C"
  elif 60<= marks <=69:
    return "D"
  else:
    return "F"
marks=(int(input("Enter Marks")))
print("Grade:",calculator_grade(marks))

#Leap year checker
def is_leap_year(year):
  if year / 400==0:
    print("leap year")
  elif year / 100==0:
    print("not leap year")
  elif year / 4==0:
    print("leap year")
  else:
    print("not leap year")
year=(int(input("Enter a year")))
print(is_leap_year(year))

#Multiplication
def print_table(num):
  for i in range(1,11):
    print(f"{num} x {i} = {num*i}")
num=int(input("enter a number:"))
print_table(num)

def sum_n(n):
  a=0
  for i in range(1,n+1):
    a+=i
  return a
n=int(input("enter n:"))
print("sum:",sum_n(n))

def factorial(n):
  a=1
  for i in range(1,n+1):
    a*=i
  return a
n=int(input("enter n:"))
print("factorial:",factorial(n))

