# -*- coding: utf-8 -*-
"""lab day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186YoaSS6TOSqtzGG6tCrexuEUtv-ozOP
"""

name=(input("Enter employee name:"))
age=int(input("Enter a age:"))
department=(input("Enter department:"))
salary=float(input("Enter salary:"))
print("Employee details:")
print("name:",name)
print("age:",age)
print("department:",department)
print("salary:",salary)

item1=(float(input("enter price of item1:")))
item2=(float(input("enter price of item2:")))
item3=(float(input("enter price of item3:")))
item4=(float(input("enter price of item4:")))
item5=(float(input("enter price of item5:")))
total=item1+item2+item3+item4+item5
print("total price of all items:",total)

a1=(float(input("enter mark of subject 1:")))
a2=(float(input("enter mark of subject 2:")))
a3=(float(input("enter mark of subject 3:")))
a4=(float(input("enter mark of subject 4:")))
a5=(float(input("enter mark of subject 5:")))
total=a1+a2+a3+a4+a5
Percentage= (total/500)*100
print("total marks=",total)
print("percentage=",Percentage,"%")

celsius=float(input("enter temperature in celsius:"))
fahrenheit=(celsius*9/5)+32
print("temperature in fahrenheit:",fahrenheit)

recharge=(float(input("enter a recharge amount:")))
GST=(float(input("enter gst percentage:")))
gstpercentage=(recharge*GST)/100
totalamount=recharge*gstpercentage
print("gst percentage:",gstpercentage)
print("total amount:",totalamount)

balance=(float(input("enter balance amount:")))
withdrawal=(float(input("enter withdrawal amount:")))
if withdrawal <= balance:
  print("balance amount")
else:
  print("insufficent amount")

age=int(input("enter age:"))
if age>=18:
  print("eligible for voting")
else:
  print("not eligible for voting")

username=(input("enter username:"))
password=(input("enter password:"))
if username=="admin" and password=="kookie":
  print("login successful")
else:
  print("invalid username or password")



unit=(int(input("enter a electricity bill:")))
if 0<= unit <=100:
  print("₹2 per unit")
elif 101<= unit <=300:
  print("₹4 per unit")
else:
  print("₹6 per unit")

age=(int(input("enter age:")))
weight=(int(input("enter weight:")))
if age<=20:
  if weight<=50:
    print("eligible for blood donation")
  else:
    print("not eligible for blood donation")
else:
  print("not eligible for blood donation")

price=float(input("enter purchase price:"))
if price > 1000:
   discount = price*0.10
elif price > 5000:
   discount = price*0.20
else:
  discount = 0
total_price = price -discount
print("discount:",discount)
print("total price:",total_price)

age=(int(input("enter age:")))
fare=(float(input("enter ticket fare:")))
if age<17:
  discount=fare*0.60
  print("child discount applied")
elif age>=60:
  discount=fare*0.30
  print("senior citizen discount applied")
else:
  discount=0
  print("no discount")
finial_fare=fare-discount
print("final fare:",finial_fare)

age=int(input("enter age:"))
if age>=18:
  print("eligible for adult movie")
else:
  print("not eligible for adult movie")

salary=float(input("enter monthly salary:"))
age=int(input("enter age:"))
work_experience=int(input("enter work experience:"))
if age >= 22 and work_experience >= 2 and salary >= 15000:
  print("eligible for loan")
else:
  print("not eligible for loan")

distance=float(input("enter distance(km):"))
if distance<=2:
  fare=distance*20
elif distance<=5:
  fare=distance*50
else:
  fare=distance*70
print("cab fare:",fare)